### PR TITLE
fixes and extensions

### PR DESCRIPTION
**Pull request by phi-gamma**
This is a collection of bugfixes and some MIDL specific additions
that I needed to process certain IDL definitions from Samba.

I hope it’s ok to lump these together into a single PR as the
commits should be self-contained.

### CODE REVIEW

**Comment by xavierleroy** [comment]
Thank you very much for this PR.  CamlIDL has been dormant for a while, so it's nice to see external contribution.

I had a quick look at the changes and they look good to me.

Perhaps @jakoblichtenberg could have a look as well?  If he's not available I'll merge in a couple of weeks.

**Comment by jakoblichtenberg** [comment]
I did not do a code review, but I imported the feature branch into our ingestion system.  Was able to build all our products.  Was able to run our standard OCaml ingestion tests.  No issues discovered.

**Comment by xavierleroy** [comment]
Thank you very much, @jakoblichtenberg , for the independent testing.  Time to merge!

**Comment by phi-gamma** [comment]
Thank you!

**Pull request merged**
