### PR TITLE
switch to dune

### PR DESCRIPTION
**Pull request by olafhering**
issues:
- missing runtest target
- missing com.* (might be no issue)

Signed-off-by: Olaf Hering <olaf@aepfle.de>

### CODE REVIEW

**Comment by olafhering** [comment]
@diml
any idea how to install the header file into `${libdir}/caml/` insteald of `${libdir}/${pkgname}`?
Other packages, like astrada/ocamlfuse@92ee0b29dca22a1a342e1c12bcfff14eeed43a43, use `#include <caml/camlidlruntime.h>` and fail:
````
Fuse_util.c:36:10: fatal error: caml/camlidlruntime.h: No such file or directory
````

**Comment by ghost** [comment]
You can always install the files manually via an `install` stanza and use `(section lib_root)`:

```scheme
(install
 (section lib_root)
 (files (camlidlruntime.h as caml/camlidlruntime.h)))
```

**Comment by xavierleroy** [comment]
I apologize if I sound ungrateful, but I see no reason to switch CamlIDL to use dune.  I think it would be problematic for some mature Windows-based projects that use CamlIDL and certainly don't want to install more dependencies just to be able to build CamlIDL.

**Comment by olafhering** [comment]
No problem. I will upgrade this branch further to cover also Windows at some point, but I can not runtime test it.

**Comment by ghost** [comment]
I don't want to push for this, but just for the record, for OCaml users Dune is a smaller dependency than `make`. Indeed, even on Windows the only dependency of Dune is a working OCaml compiler. In particular, you can build and use Dune directly from cmd.exe without anything else.

**Pull request closed without merging**
